name: Copy files to another repo

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the "source" repository (current repo)
    - name: Checkout source repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Step 2: Clone the target repository
    - name: Clone target repo
      run: |
        git clone https://$GITHUB_ACTOR:${{ secrets.PAT }}@github.com/FarhanCeo/sync-repo-target.git target-repo

    # Step 3: Copy all files from the "source" repo to the "target-repo"
    - name: Copy files
      run: |
         rsync -av --progress --exclude target-repo ./ ./target-repo/

    # Step 4: Commit and push the changes to the target repository
    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Copy files from source repo"
        git push origin main
