name: Clone Repository to Another Repo

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or any branch you want to trigger the action

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Clone target repository
      run: |
        git clone --bare https://github.com/FarhanCeo/sync-repo-source.git
        cd sync-repo-source.git
        git push --mirror https://$GH_TOKEN@github.com/FarhanCeo/sync-repo-target.git
